//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bookstoreEntities : DbContext
    {
        public bookstoreEntities()
            : base("name=bookstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Magazines> Magazines { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
    
        public virtual int sp_searchauthororpublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_searchauthororpublisher");
        }
    
        public virtual ObjectResult<sp_searchlanguage_Result> sp_searchlanguage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_searchlanguage_Result>("sp_searchlanguage");
        }
    
        public virtual ObjectResult<sp_searchauthororpublisher1_Result> sp_searchauthororpublisher1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_searchauthororpublisher1_Result>("sp_searchauthororpublisher1");
        }
    }
}
