//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Bookid { get; set; }
        public string Title { get; set; }
        public Nullable<int> Authorid { get; set; }
        public Nullable<int> Publisherid { get; set; }
        public string Languages { get; set; }
        public string Dimensions { get; set; }
        public Nullable<decimal> Weights { get; set; }
        public int Prints { get; set; }
        public int ISBN { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Publishers Publishers { get; set; }
    }
}
